# Generated by Django 5.0.1 on 2024-01-07 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(choices=[('RE', 'Repairman'), ('CT', 'Car transport'), ('ES', 'Electrical specialist'), ('OC', 'Oil Change'), ('P', 'Puncture'), ('CS', 'Car smoothing'), ('CP', 'Car painter'), ('U', 'Upholstery')], max_length=20)),
                ('descriptoin', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('created', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
    ]
