# Generated by Django 5.0.1 on 2024-01-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='job_type',
            field=models.CharField(choices=[('MR', 'Mechanical Repair'), ('PC', 'Puncture Catcher'), ('CG', 'Car Glass'), ('ER', 'Electrical Repair'), ('BW', 'Body Work'), ('PT', 'Painting'), ('TR', 'Transmission Repair'), ('OC', 'Oil Change'), ('TW', 'Towing'), ('OT', 'Other')], default='OT', max_length=2),
        ),
    ]
