# Generated by Django 5.0.1 on 2024-01-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_description_alter_user_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(choices=[('آبیک', 'Abyek')], default='آبیک', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='job_type',
            field=models.CharField(choices=[('تعمیرکار', 'Mechanical Repair'), ('آپاراتی', 'Puncture Catcher'), ('شیشه اتوموبیل', 'Car Glass'), ('برق خودرو', 'Electrical Repair'), ('صافکار', 'Body Work'), ('نقاش', 'Painting'), ('متخصص گیربکس', 'Transmission Repair'), ('تعویض روعنی', 'Oil Change'), ('یدک کش', 'Towing'), ('سایر', 'Other')], default='سایر', max_length=20),
        ),
    ]
