# Generated by Django 5.0.1 on 2024-01-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_city_alter_user_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job_type',
            field=models.CharField(choices=[('تعمیرکار', 'Mechanical Repair'), ('آپاراتی', 'Puncture Catcher'), ('شیشه اتوموبیل', 'Car Glass'), ('برق خودرو', 'Electrical Repair'), ('صافکار', 'Body Work'), ('نقاش', 'Painting'), ('متخصص گیربکس', 'Transmission Repair'), ('تعویض روغن', 'Oil Change'), ('یدک کش', 'Towing'), ('سایر', 'Other')], default='سایر', max_length=20),
        ),
    ]
