# Generated by Django 5.0.1 on 2024-01-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_job_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpcoderegister',
            name='phone',
        ),
        migrations.AddField(
            model_name='otpcoderegister',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
