# Generated by Django 5.0.1 on 2024-01-23 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_otpcoderegister_phone_otpcoderegister_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcoderegister',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
