# Generated by Django 5.0.1 on 2024-01-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('created',), 'verbose_name': 'article', 'verbose_name_plural': 'articles'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ('created',), 'verbose_name': 'gallery', 'verbose_name_plural': 'galleries'},
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default=1, upload_to='article-pic/'),
            preserve_default=False,
        ),
    ]
